#!/usr/bin/env python3
"""Generate one machine-readable YAML schema instance for every Markdown graph node.

Markdown remains the source of truth. This script consumes generated/nodes.json
from scripts/audit-graph.py and mirrors every node into schema/nodes/<source>.yaml.
The generated files are deterministic and safe to commit.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import shutil
import sys
from collections import Counter

TYPE_ALIASES = {"university": "school"}
PRIORITY_KEYS = [
    "type", "name", "title", "english_name", "aliases", "canonical",
    "current_affiliations", "company", "companies", "organization", "team",
    "model", "communities", "projects", "areas", "roles", "layer", "category",
    "focus", "repository", "open_source", "public_repo", "hardware", "governance",
    "confidence", "last_verified", "relations",
]


def as_list(value):
    if value is None or value == "":
        return []
    if isinstance(value, list):
        return [item for item in value if item not in (None, "")]
    return [value]


def merge_unique(*values):
    merged = []
    seen = set()
    for value in values:
        for item in as_list(value):
            marker = json.dumps(item, ensure_ascii=False, sort_keys=True) if isinstance(item, (dict, list)) else str(item)
            if marker in seen:
                continue
            seen.add(marker)
            merged.append(item)
    return merged


def normalize_frontmatter(node: dict) -> tuple[str, dict]:
    raw_type = str(node.get("type") or "note")
    node_type = TYPE_ALIASES.get(raw_type, raw_type)
    data = dict(node.get("frontmatter") or {})
    data["type"] = node_type

    if not data.get("name"):
        data["name"] = node.get("name") or pathlib.PurePosixPath(str(node.get("id") or "node")).name

    if node_type in {"person", "person-link"}:
        current = merge_unique(
            data.get("current_affiliations"), data.get("affiliations"), data.get("affiliation"),
            data.get("companies"), data.get("company"),
        )
        if current:
            data["current_affiliations"] = current
        for legacy in ("affiliations", "affiliation", "companies", "company"):
            data.pop(legacy, None)

    if node_type == "project":
        companies = merge_unique(data.get("companies"), data.get("company"))
        if companies or "companies" in data or "company" in data:
            data["companies"] = companies
        data.pop("company", None)

    if node_type == "community":
        if not data.get("repository") and data.get("github"):
            data["repository"] = data.get("github")
        data.pop("github", None)

    if node_type == "model-project" and not data.get("model"):
        data["model"] = data.get("name")

    return node_type, data


def required_fields(schema_text: str) -> list[str]:
    fields = []
    in_required = False
    for raw in schema_text.splitlines():
        if raw.strip() == "required:" and not raw.startswith(" "):
            in_required = True
            continue
        if not in_required:
            continue
        if raw.startswith("  - "):
            fields.append(raw[4:].strip())
            continue
        if raw and not raw.startswith(" "):
            break
    return fields


def json_yaml(value) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def dump_instance(metadata: dict, data: dict) -> str:
    lines = ["# Generated from Markdown. Do not edit this file by hand.", f"_schema: {json_yaml(metadata)}"]
    emitted = set()
    for key in PRIORITY_KEYS:
        if key in data:
            lines.append(f"{key}: {json_yaml(data[key])}")
            emitted.add(key)
    for key in sorted(k for k in data if k not in emitted):
        lines.append(f"{key}: {json_yaml(data[key])}")
    return "\n".join(lines) + "\n"


def output_path(output_root: pathlib.Path, source_path: str) -> pathlib.Path:
    source = pathlib.PurePosixPath(source_path).with_suffix("")
    return output_root.joinpath(*source.parts).with_suffix(".yaml")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=".")
    parser.add_argument("--nodes", default="generated/nodes.json")
    parser.add_argument("--output", default="schema/nodes")
    parser.add_argument("--manifest", default="schema/node-manifest.json")
    args = parser.parse_args()

    root = pathlib.Path(args.root).resolve()
    nodes_path = (root / args.nodes).resolve()
    output_root = (root / args.output).resolve()
    manifest_path = (root / args.manifest).resolve()

    if not nodes_path.exists():
        raise SystemExit(f"Missing {nodes_path}; run scripts/audit-graph.py first")
    if output_root == root or root not in output_root.parents:
        raise SystemExit("Refusing to generate outside a repository subdirectory")

    nodes = json.loads(nodes_path.read_text(encoding="utf-8"))
    if not isinstance(nodes, list) or not nodes:
        raise SystemExit("nodes.json is empty or invalid")

    prepared = []
    missing_schema_types = set()
    for node in nodes:
        source_path = str(node.get("path") or "")
        if not source_path.endswith(".md"):
            raise SystemExit(f"Node has invalid source path: {source_path!r}")
        source_file = root / source_path
        if not source_file.exists():
            raise SystemExit(f"Markdown source is missing: {source_path}")
        node_type, data = normalize_frontmatter(node)
        schema_rel = f"schema/{node_type}.yaml"
        if not (root / schema_rel).exists():
            missing_schema_types.add(node_type)
        prepared.append((node, source_path, source_file, node_type, data, schema_rel))

    if missing_schema_types:
        print("Missing schema definitions for node types:")
        for node_type in sorted(missing_schema_types):
            print(f"- {node_type}: expected schema/{node_type}.yaml")
        print("Add every missing schema and register it in schema/catalog.yaml.")
        return 1

    if output_root.exists():
        shutil.rmtree(output_root)
    output_root.mkdir(parents=True, exist_ok=True)

    schema_cache: dict[str, list[str]] = {}
    rows = []
    type_counts = Counter()
    incomplete = 0

    for node, source_path, source_file, node_type, data, schema_rel in prepared:
        if node_type not in schema_cache:
            schema_cache[node_type] = required_fields((root / schema_rel).read_text(encoding="utf-8"))
        required = schema_cache[node_type]
        missing = [field for field in required if data.get(field) in (None, "", [])]
        if missing:
            incomplete += 1

        destination = output_path(output_root, source_path)
        destination.parent.mkdir(parents=True, exist_ok=True)
        metadata = {
            "definition": schema_rel,
            "source_markdown": source_path,
            "source_sha256": hashlib.sha256(source_file.read_bytes()).hexdigest(),
            "node_id": node.get("id"),
            "status": "complete" if not missing else "incomplete",
            "missing_required": missing,
        }
        destination.write_text(dump_instance(metadata, data), encoding="utf-8")

        rows.append({
            "id": node.get("id"),
            "type": node_type,
            "source_markdown": source_path,
            "schema_definition": schema_rel,
            "schema_instance": destination.relative_to(root).as_posix(),
            "status": metadata["status"],
            "missing_required": missing,
        })
        type_counts[node_type] += 1

    rows.sort(key=lambda item: str(item["source_markdown"]).casefold())
    manifest = {
        "format": "ai-infra-relationship/node-schema-manifest-v1",
        "source_of_truth": "markdown",
        "node_count": len(rows),
        "complete_count": len(rows) - incomplete,
        "incomplete_count": incomplete,
        "counts_by_type": dict(sorted(type_counts.items())),
        "nodes": rows,
    }
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    print(
        f"Generated {len(rows)} node schema instances in {output_root.relative_to(root)}; "
        f"{len(rows) - incomplete} complete, {incomplete} incomplete."
    )
    for row in rows:
        if row["missing_required"]:
            print(f"WARN: {row['source_markdown']}: missing required {', '.join(row['missing_required'])}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
